/**
 * Codegen: scans src/modules/<id>/module.ts and writes src/modules/_generated.ts
 * exporting every module. This keeps module registration zero-touch — adding a
 * folder requires NO edit to any shared file (so dozens of modules can be built
 * in parallel without merge conflicts). The generated file is git-ignored.
 */
import { readdirSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const modulesDir = join(here, '..', 'src', 'modules');

const entries = readdirSync(modulesDir).filter((name) => {
  const full = join(modulesDir, name);
  if (!statSync(full).isDirectory()) return false;
  return existsSync(join(full, 'module.ts'));
});
entries.sort();

const imports = entries
  .map((name, i) => `import m${i} from './${name}/module';`)
  .join('\n');
const list = entries.map((_, i) => `  m${i},`).join('\n');

const content = `// AUTO-GENERATED by scripts/gen-modules.ts. Do not edit.
import type { HospitalModule } from './types';
${imports}

export const modules: HospitalModule[] = [
${list}
];
`;

writeFileSync(join(modulesDir, '_generated.ts'), content);
console.log(`[gen-modules] wrote ${entries.length} module(s): ${entries.join(', ') || '(none)'}`);
